sudo: required
matrix:
  include:
    - language: node_js
      cache:
        directories:
          - node_modules
      env:
        - secure: "y3S8xrdLufs0wL/VtgMMXcDQxAtbZeydvGGBNRVA+8XraiqcWatgEQZkVnxQ4MTMywlm7lDPZhYLxvFprLzx/lgjIq2K2NTwixND4LcOUG2jJo5lsL7GfMQYjhZyyoJIVpuC3TCRh2LNBNt532c9HxtIPZkOR3/Cm3JrBidOiUe0lCcWI74OZGx4RLSia+Zv4E8rcriuKn3uEbMWZWciJccsdPrCgrLBnfiUgrwOmqhewcwYONDMwyds1ZDrL+bXm8xhCrOFKfQKW85AS6uhZ6xJz/6LCjQr1ETUXh7QulX5UG1gjgM1lc3+DRILSiDZLztGHiSnxcBd1XlGacQkFKaXC7NjDPJ7mQBtqwbkg+tSIeQsP2BALwjeerUYfgHidqXFh2WZt4tVxITJNMD4wmrnN8V2zdFyTbg2SiaeCrSPxPYPM4qlilRRPA/vDMyYwRuklClj3jFWqKElG25ZSiexb7Lv87Bdk0OnOGHBsyM3IMix8aywAnA4S6rt5A9lfXZqmJHYA0MTtXYrRRwr28nF06sMryBOQGFtdZyMOB+BaIl2JYrbj19pLWPkY+xIC/4KMr7GPhRiHVXz3pebdNnH6Kt6QLUSyiCfPWP5lGCFTRufDFzvRHrhNX8UJSZJdjuSiZgIL5J6bJudJngqPYJgIuMQIZ6bLfqo+9jdPAo="
      node_js: '8'
      before_install:
        - npm i -g yarn
      install:
        - yarn
      script:
        - yarn ci-check
      before_deploy:
        - yarn build
      deploy:
        provider: npm
        email: cychiuae@connect.ust.hk
        api_key: $NPM_PUBLISH_TOKEN
        skip_cleanup: true
        on:
          tags: true

    - language: objective-c
      os: osx
      osx_image: xcode9.4
      env:
        - TRAVIS_NODE_VERSION="8.9.0"
      before_install:
        - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
        - npm i -g yarn
        - npm i -g react-native-cli
      install:
        - yarn
      script:
        - ./scripts/integration_test.sh ios

    - language: android
      jdk: oraclejdk8
      android:
        components:
          - tools
          - tools
          - platform-tools
          - build-tools-27.0.3
          - android-22
          - extra-android-support
          - extra-android-m2repository
          - extra-google-m2repository
          - sys-img-armeabi-v7a-android-22
        licenses:
          - android-sdk-preview-license-.+
          - android-sdk-license-.+
          - google-gdk-license-.+
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - $HOME/.android/build-cache
      env:
        - TRAVIS_NODE_VERSION="8.9.0"
      before_install:
        - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
        - npm i -g yarn
        - npm i -g react-native-cli
        - yes | sdkmanager "platforms;android-27"
      install:
        - yarn
      script:
        - ./scripts/integration_test.sh android

notifications:
  slack:
    rooms:
      secure: EIv/UeMqijx3v7mYXlDf2yDkd2sU+FtQewb+P0OG0yePumHqDfH1Ka5v1MznjuVJwSMP/iQOQ4dzWGOV+sE+FCP9boNVoOX41jiD3TfSXTDVbZ5t4iSwSEfzrfo7wC6l0+HZ5CXHbui5DyfMSMv4KdhNOf9CrvBrAtIOghK/PZlBaPuTMq99gQxdaLqej+HB0+G0EDOzcY7FycFFjTUufCutcqJTHB8i9VsHTyO6K2dFT8TZ2ScT7tJX85zVhcQM486gr/fyGmmQH/bUGna7qO2HEK7ej+IWLBu2m6ApdOvZbVGk4M7RR6f52OUHneVSNLRkjY5qcrkVxc9rmhwbkxV5oxmWu+bPQ+aot+cIdSBESV9L8GDANy8W76/Fjv0WluDpcfyaA1oU9VFbMJ7+Ndciu2Cudh0E+BWUiXhcRXHH7bfEob9iZDmEyky1ctjADa2qfD5c9MhAGGRBreDC7i/QrDzt+slkIxfRLyEYN/V3BkzxPP4UoSnRperNA7mZbsXSJKtLruzVVZRmTn+nNjngx2lf3Z4SfB5xIz+2YXuuqVG3T/xRNfo6GPwfA9Qax3BXJ0qTFQ9AoXgJdXcrkXKkTq1AcOvr88kS5EAgdLp0RCMXKJFX4tT+pTgLQh3niagy0j0tclb9eVdnE8J+ntE+NQSrZ3B2PdWEG3/rwDU=
